/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StationsRouteImport } from './routes/stations'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as NewsArticleIdRouteImport } from './routes/news_.$articleId'
import { Route as MarketplaceRentRouteImport } from './routes/marketplace.rent'
import { Route as MarketplaceSellIndexRouteImport } from './routes/marketplace.sell.index'
import { Route as MarketplaceBuyIndexRouteImport } from './routes/marketplace.buy.index'
import { Route as MarketplaceSellCarIdRouteImport } from './routes/marketplace.sell.$carId'
import { Route as MarketplaceBuyCarIdRouteImport } from './routes/marketplace.buy.$carId'

const StationsRoute = StationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketplaceRoute,
} as any)
const NewsArticleIdRoute = NewsArticleIdRouteImport.update({
  id: '/news_/$articleId',
  path: '/news/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRentRoute = MarketplaceRentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceSellIndexRoute = MarketplaceSellIndexRouteImport.update({
  id: '/sell/',
  path: '/sell/',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceBuyIndexRoute = MarketplaceBuyIndexRouteImport.update({
  id: '/buy/',
  path: '/buy/',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceSellCarIdRoute = MarketplaceSellCarIdRouteImport.update({
  id: '/sell/$carId',
  path: '/sell/$carId',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceBuyCarIdRoute = MarketplaceBuyCarIdRouteImport.update({
  id: '/buy/$carId',
  path: '/buy/$carId',
  getParentRoute: () => MarketplaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/news': typeof NewsRoute
  '/services': typeof ServicesRoute
  '/stations': typeof StationsRoute
  '/marketplace/rent': typeof MarketplaceRentRoute
  '/news/$articleId': typeof NewsArticleIdRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/marketplace/buy/$carId': typeof MarketplaceBuyCarIdRoute
  '/marketplace/sell/$carId': typeof MarketplaceSellCarIdRoute
  '/marketplace/buy/': typeof MarketplaceBuyIndexRoute
  '/marketplace/sell/': typeof MarketplaceSellIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/news': typeof NewsRoute
  '/services': typeof ServicesRoute
  '/stations': typeof StationsRoute
  '/marketplace/rent': typeof MarketplaceRentRoute
  '/news/$articleId': typeof NewsArticleIdRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/marketplace/buy/$carId': typeof MarketplaceBuyCarIdRoute
  '/marketplace/sell/$carId': typeof MarketplaceSellCarIdRoute
  '/marketplace/buy': typeof MarketplaceBuyIndexRoute
  '/marketplace/sell': typeof MarketplaceSellIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/news': typeof NewsRoute
  '/services': typeof ServicesRoute
  '/stations': typeof StationsRoute
  '/marketplace/rent': typeof MarketplaceRentRoute
  '/news_/$articleId': typeof NewsArticleIdRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/marketplace/buy/$carId': typeof MarketplaceBuyCarIdRoute
  '/marketplace/sell/$carId': typeof MarketplaceSellCarIdRoute
  '/marketplace/buy/': typeof MarketplaceBuyIndexRoute
  '/marketplace/sell/': typeof MarketplaceSellIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/marketplace'
    | '/news'
    | '/services'
    | '/stations'
    | '/marketplace/rent'
    | '/news/$articleId'
    | '/marketplace/'
    | '/marketplace/buy/$carId'
    | '/marketplace/sell/$carId'
    | '/marketplace/buy/'
    | '/marketplace/sell/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/news'
    | '/services'
    | '/stations'
    | '/marketplace/rent'
    | '/news/$articleId'
    | '/marketplace'
    | '/marketplace/buy/$carId'
    | '/marketplace/sell/$carId'
    | '/marketplace/buy'
    | '/marketplace/sell'
  id:
    | '__root__'
    | '/'
    | '/marketplace'
    | '/news'
    | '/services'
    | '/stations'
    | '/marketplace/rent'
    | '/news_/$articleId'
    | '/marketplace/'
    | '/marketplace/buy/$carId'
    | '/marketplace/sell/$carId'
    | '/marketplace/buy/'
    | '/marketplace/sell/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  NewsRoute: typeof NewsRoute
  ServicesRoute: typeof ServicesRoute
  StationsRoute: typeof StationsRoute
  NewsArticleIdRoute: typeof NewsArticleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stations': {
      id: '/stations'
      path: '/stations'
      fullPath: '/stations'
      preLoaderRoute: typeof StationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/news_/$articleId': {
      id: '/news_/$articleId'
      path: '/news/$articleId'
      fullPath: '/news/$articleId'
      preLoaderRoute: typeof NewsArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/rent': {
      id: '/marketplace/rent'
      path: '/rent'
      fullPath: '/marketplace/rent'
      preLoaderRoute: typeof MarketplaceRentRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/sell/': {
      id: '/marketplace/sell/'
      path: '/sell'
      fullPath: '/marketplace/sell/'
      preLoaderRoute: typeof MarketplaceSellIndexRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/buy/': {
      id: '/marketplace/buy/'
      path: '/buy'
      fullPath: '/marketplace/buy/'
      preLoaderRoute: typeof MarketplaceBuyIndexRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/sell/$carId': {
      id: '/marketplace/sell/$carId'
      path: '/sell/$carId'
      fullPath: '/marketplace/sell/$carId'
      preLoaderRoute: typeof MarketplaceSellCarIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/buy/$carId': {
      id: '/marketplace/buy/$carId'
      path: '/buy/$carId'
      fullPath: '/marketplace/buy/$carId'
      preLoaderRoute: typeof MarketplaceBuyCarIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
  }
}

interface MarketplaceRouteChildren {
  MarketplaceRentRoute: typeof MarketplaceRentRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  MarketplaceBuyCarIdRoute: typeof MarketplaceBuyCarIdRoute
  MarketplaceSellCarIdRoute: typeof MarketplaceSellCarIdRoute
  MarketplaceBuyIndexRoute: typeof MarketplaceBuyIndexRoute
  MarketplaceSellIndexRoute: typeof MarketplaceSellIndexRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceRentRoute: MarketplaceRentRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  MarketplaceBuyCarIdRoute: MarketplaceBuyCarIdRoute,
  MarketplaceSellCarIdRoute: MarketplaceSellCarIdRoute,
  MarketplaceBuyIndexRoute: MarketplaceBuyIndexRoute,
  MarketplaceSellIndexRoute: MarketplaceSellIndexRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  NewsRoute: NewsRoute,
  ServicesRoute: ServicesRoute,
  StationsRoute: StationsRoute,
  NewsArticleIdRoute: NewsArticleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
